### ISSUE TITLE
Issue with location 

### ISSUE THREAD

**Issue by ripley06** [SkriptLang/skript-docs#42]
![Screen Shot](https://github.com/SkriptLang/skript-docs/assets/134252372/6ba456d9-da4a-493c-8f8f-79935fb2268a)

Just updated to the last version which is 2.7.0 beta2 and found this issue. Console says that I don't have a location in the command event but next to that is the skript i'm using that clearly shows the location. How do I fix this or should I revert back to a earlier version.

**Comment by Fusezion** [comment]
This isn't the discord please use https://discord.gg/skript for help, if it's determined to be an actual skript issue you will be pointed towards the correct direction after
