### ISSUE TITLE
[BUG] the isNew system doesn't account for additions to Since tag

### ISSUE THREAD

**Issue by Fusezion** [SkriptLang/skript-docs#48]
In 2.7 skript updated ExprSets (named "Sets") to include enum classinfos, when you click on `isNew` button to limit it to all 2.7 syntax "Sets" doesn't appear as shown in the image, this is likely caused by doing an exact search for `@Since("2.7")` and not checking if it contains it.

![image](https://github.com/SkriptLang/skript-docs/assets/81952476/0987bcfc-8548-44e2-b5b4-e48dd35b4602)

Calling this a bug as I don't believe this was intended behavior and just went unnoticed.

**Comment by AyhamAl-Ali** [comment]
Probably caused by 
https://github.com/SkriptLang/skript-docs/blob/aa1dbf7198d5931ac414215750350a4bf9d2ee86/docs/js/main.js#L251
not splitting the versions for proper checking

I will create a PR to handle this and cleanup the search function
