### ISSUE TITLE
[BUG] SkriptLang testing environment syntax is leaking through

### ISSUE THREAD

**Issue by Fusezion** [SkriptLang/skript-docs#49]
Some of SkriptLang's testing environment syntax like `CondMethodExists` has leaked through and into the release documentations, unsure what else there is that is from it.
![image](https://github.com/SkriptLang/skript-docs/assets/81952476/233921dd-8ccb-46ef-a63a-6339ebc8742d)
![image](https://github.com/SkriptLang/skript-docs/assets/81952476/1cede7db-6eba-4a4d-882d-1025a9d651c5)

**Comment by AyhamAl-Ali** [comment]
Nothing is leaked, it just doesn't have `@NoDoc` annotation.
