### ISSUE TITLE
Expression - ExprName | 2 Expressions?

### ISSUE THREAD

**Issue by Fusezion** [SkriptLang/skript-docs#5]
Not sure really what to call this nor how to give a better explanation the site seems to just cut them into 2 expressions instead of as a single one, this might be caused by skript's end of stuff \*last image as we register 2 expressions using this class

**Links**
https://docs.skriptlang.org/expressions.html?search=#ExprName
https://docs.skriptlang.org/expressions.html?search=#ExprName-2
\*above one bugs out but it's whats given when you copy link

![image](https://user-images.githubusercontent.com/81952476/213973300-18b922c0-2272-410d-9e06-eff925cc9230.png)
![image](https://user-images.githubusercontent.com/81952476/213973697-4f23abd2-51f7-409d-b8c4-0a634c53df0e.png)
![image](https://user-images.githubusercontent.com/81952476/213973665-834f714e-702b-46e6-9db7-0a9a5345b80d.png)
![image](https://user-images.githubusercontent.com/81952476/213974043-4b65dcbb-2b07-4c42-a725-42e071368f23.png)

**Comment by AyhamAl-Ali** [comment]
This is fine, it's registered twice in code for a reason (players/offlineplayers)
This either stays as is (which is okay but could be improved) or expression gets splitted into 2-3 expressions (ExprName/ExprTabName/ExprListName)

**Comment by Fusezion** [comment]
I do believe something should be done about its stuff linking to it as it's impossible to get a link for the 2nd expression with current search

**Comment by AyhamAl-Ali** [comment]
Search filter failing due to 
https://github.com/SkriptLang/skript-docs/blob/2712b50e496fd1d426f426ad6978973712dc0807/docs/js/main.js#L235

This can be easily fixed
