### ISSUE TITLE
weird layout bug when cookie banner visible

### ISSUE THREAD

**Issue by bluelhf** [SkriptLang/skript-docs#53]
![layout bug, elements visible above search bar and top header](https://github.com/SkriptLang/skript-docs/assets/52505120/7c06d499-a4b3-4f5e-bfa9-c2e230050c7e)

caused by cookie banner having `position: sticky;` instead of `position: absolute; width: 100%;`

**Comment by AyhamAl-Ali** [comment]
You're using my own version which haven't been updated in like 5 months 😬 
Try to reproduce it on https://docs.skriptlang.org/

**Comment by bluelhf** [comment]
:grimacing: yeah, doesn't happen on docs.skriptlang.org
