### ISSUE TITLE
Forgot to update some INSERT VERSION tags for 2.7

### ISSUE THREAD

**Issue by Fusezion** [SkriptLang/skript-docs#54]
Don't really think I need to go into too much detail, 3 classes didn't get updated for `INSERT VERSION` before updating docs sites.

https://docs.skriptlang.org/docs.html?search=#inventory_drag
https://docs.skriptlang.org/docs.html?search=#EffPotion
https://docs.skriptlang.org/docs.html?search=#CondIsInfinite

**Comment by sovdeeth** [comment]
Actually a Skript issue, not a docs issue, see [#6027](https://github.com/SkriptLang/Skript/pull/6027)
