### ISSUE TITLE
404 on https://docs.skriptlang.org/strings/

### ISSUE THREAD

**Issue by AutonomousCat** [SkriptLang/skript-docs#58]
The link is on this page: https://docs.skriptlang.org/classes.html#string
![wNOpHE4cwC](https://github.com/SkriptLang/skript-docs/assets/130127508/1a868486-ded9-4635-a3b5-3dcc4ab36d7a)
![image](https://github.com/SkriptLang/skript-docs/assets/130127508/fd0cc063-a8ec-43ee-8d67-a188ba56a4a5)

**Comment by Fusezion** [comment]
ah it's not that it's 404 it's just directing to incorrect page I believe the target page should be https://docs.skriptlang.org/text.html
so it should be changing the `./strings/` to the `./text.html`

*unsure why this isn't formatting for code snippet*
https://github.com/SkriptLang/Skript/blob/b9f89c14c6cd7859b96a0c6a7d791fdb455c09d6/src/main/java/ch/njol/skript/classes/data/JavaClasses.java#L550-L553

**Comment by AyhamAl-Ali** [comment]
Thank you author for reporting this and thanks Fuse for the explanation, I have marked it as `good first issue` since it's easy fix if anyone would like to contribute.

**Comment by RamonJales** [comment]
Hello, can i fix this issue?

**Comment by EquipableMC** [comment]
Your more then welcomed to. It's an open sourced project after all

**Comment by RamonJales** [comment]
Thanks! I fixed it and sent a PR.

**Comment by APickledWalrus** [comment]
Fixed in 2.8.1
